name: Build and Push Multi-Platform Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker: 
          - { name: "front_nuxt", path: "./norman" }
          - { name: "back_elixir", path: "./users_api" }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "Kvpqpl6n$" | docker login -u "thomas1212" --password-stdin

      - name: Delete Docker image from Docker Hub - back_elixir
        run: |
          curl -X DELETE "https://hub.docker.com/v2/repositories/thomas1212/back_elixir/tags/latest/" \
            -H "Authorization: JWT dckr_pat_y9XWIeW8mNtD6QJuBvchoRh03tc"

      - name: Delete Docker image from Docker Hub - front_nuxt
        run: |
          curl -X DELETE "https://hub.docker.com/v2/repositories/thomas1212/front_nuxt/tags/latest/" \
            -H "Authorization: JWT dckr_pat_y9XWIeW8mNtD6QJuBvchoRh03tc"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker.path }}
          file: ${{ matrix.docker.path }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thomas1212/${{ matrix.docker.name }}:latest
